import {defaultGrade,type Grade} from '../scenes/ColorGradePass';
export class ColorPanel{
 private value=defaultGrade();private panel:HTMLElement;private channel:keyof Grade['curves']='master';private band=0;private bypass=false;
 constructor(private apply:(g:Grade)=>void){
  const button=document.createElement('button');button.id='color-settings';button.textContent='◐ 调色实验室';document.querySelector('.pause-panel .weather-actions')!.prepend(button);
  this.panel=document.createElement('section');this.panel.id='color-panel';this.panel.hidden=true;this.panel.innerHTML=`<header><b>调色实验室</b><button id="color-close">返回</button></header><small>实时预览 · 仅本地参数</small><details open><summary>曝光 / 色彩</summary><div id="grade-basic"></div></details><details><summary>HSL 分色调整</summary><select id="grade-band" aria-label="HSL 色段">${['红','黄','绿','青','蓝','紫'].map((v,i)=>`<option value="${i}">${v}</option>`).join('')}</select><div id="grade-hsl"></div></details><details><summary>色调曲线</summary><select id="grade-channel" aria-label="曲线通道">${[['master','总曲线'],['red','红通道'],['green','绿通道'],['blue','蓝通道']].map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}</select><svg id="grade-curve" viewBox="0 0 256 144" aria-label="拖动曲线控制点调整输出亮度"><path d="M8 136L248 8 M8 72H248 M128 8V136" stroke="#6d8c7b" fill="none"/><polyline fill="none" stroke="#ffe3a0" stroke-width="2"/>${[0,1,2,3,4].map(i=>`<circle data-point="${i}" r="5" fill="#ffe3a0"/>`).join('')}</svg><div id="grade-points"></div><small>输入位置固定，调节输出；分段线性插值。</small></details><div class="grade-actions"><button id="grade-compare" aria-pressed="false">对比原图</button><button id="grade-reset">恢复默认</button><button id="grade-copy">复制参数</button></div><textarea id="grade-json" readonly aria-label="调色参数 JSON"></textarea><output id="grade-status" role="status"></output>`;
  document.getElementById('pause-menu')!.append(this.panel);
  const fields:[keyof Grade,string,number,number,number][]=[['exposure','曝光 EV',-3,3,.05],['brightness','亮度',-.3,.3,.01],['contrast','对比度',.4,2,.01],['saturation','饱和度',0,2,.01],['temperature','色温（冷 → 暖）',-1,1,.01],['tint','色调（绿 → 洋红）',-1,1,.01],['shadows','阴影',-1,1,.01],['highlights','高光',-1,1,.01],['gamma','中间调 Gamma',.4,2.5,.01]];
  for(const [key,label,min,max,step] of fields)this.slider('grade-basic',key,label,min,max,step,()=>this.value[key] as number,v=>{(this.value[key] as number)=v;});
  for(const [i,label,min,max,step] of [[0,'色相',-45,45,1],[1,'饱和度',-1,1,.01],[2,'明度',-1,1,.01]] as [number,string,number,number,number][])this.slider('grade-hsl',`hsl-${i}`,label,min,max,step,()=>this.value.hsl[this.band][i],v=>{this.value.hsl[this.band][i]=v;});
  for(let i=0;i<5;i++)this.slider('grade-points',`point-${i}`,['黑场','暗部','中间调','亮部','白场'][i],0,1,.01,()=>this.value.curves[this.channel][i],v=>{this.value.curves[this.channel][i]=v;});
  button.onclick=()=>{this.panel.hidden=false;document.body.classList.add('color-editing');this.sync();document.getElementById('color-close')!.focus();};
  document.getElementById('color-close')!.onclick=()=>{this.panel.hidden=true;document.body.classList.remove('color-editing');this.bypass=false;this.changed();button.focus();};
  document.getElementById('grade-band')!.onchange=e=>{this.band=Number((e.target as HTMLSelectElement).value);this.sync();};
  document.getElementById('grade-channel')!.onchange=e=>{this.channel=(e.target as HTMLSelectElement).value as typeof this.channel;this.sync();};
  document.getElementById('grade-compare')!.onclick=()=>{this.bypass=!this.bypass;this.changed();};
  document.getElementById('grade-reset')!.onclick=()=>{this.value=defaultGrade();this.bypass=false;this.changed();};
  document.getElementById('grade-copy')!.onclick=async()=>{const area=document.getElementById('grade-json') as HTMLTextAreaElement;try{await navigator.clipboard.writeText(area.value);document.getElementById('grade-status')!.textContent='参数已复制，粘贴到聊天即可';}catch{area.focus();area.select();document.getElementById('grade-status')!.textContent='请长按或全选复制下方参数';}};
  const svg=this.panel.querySelector('svg')!;let point=-1;
  const move=(e:PointerEvent)=>{if(point<0)return;const r=svg.getBoundingClientRect(),y=(e.clientY-r.top)/r.height*144;this.value.curves[this.channel][point]=Math.round(Math.max(0,Math.min(1,(136-y)/128))*100)/100;this.changed();};
  svg.onpointerdown=e=>{const target=e.target as Element;if(!target.hasAttribute('data-point'))return;point=Number(target.getAttribute('data-point'));svg.setPointerCapture(e.pointerId);e.preventDefault();move(e);};svg.onpointermove=move;svg.onpointerup=svg.onpointercancel=()=>{point=-1;};
  new MutationObserver(()=>{if((document.getElementById('pause-menu') as HTMLElement).hidden){this.panel.hidden=true;document.body.classList.remove('color-editing');this.bypass=false;this.changed();}}).observe(document.getElementById('pause-menu')!,{attributes:true,attributeFilter:['hidden']});
  try{const saved=JSON.parse(localStorage.getItem('city-grading-draft-v1')??'null') as Grade|null;
   if(saved&&fields.every(([key,,min,max])=>typeof saved[key]==='number'&&Number.isFinite(saved[key])&&(saved[key] as number)>=min&&(saved[key] as number)<=max)&&Array.isArray(saved.hsl)&&saved.hsl.length===6&&saved.hsl.every(v=>Array.isArray(v)&&v.length===3&&v.every((n,i)=>Number.isFinite(n)&&Math.abs(n)<=(i===0?45:1)))&&saved.curves&&['master','red','green','blue'].every(k=>{const points=saved.curves[k as 'master'];return Array.isArray(points)&&points.length===5&&points.every(n=>Number.isFinite(n)&&n>=0&&n<=1);}))this.value=saved;
  }catch{/* A missing or damaged local draft leaves the neutral settings intact. */}
  this.changed();
 }
 private bindings:(()=>void)[]=[];
 private slider(parent:string,id:string,label:string,min:number,max:number,step:number,get:()=>number,set:(v:number)=>void){
  const row=document.createElement('label');row.className='grade-row';row.innerHTML=`<span>${label}</span><input id="grade-${id}" type="range" min="${min}" max="${max}" step="${step}"><input type="number" aria-label="${label}数值" min="${min}" max="${max}" step="${step}">`;document.getElementById(parent)!.append(row);const [range,number]=Array.from(row.querySelectorAll('input'));
  const update=(v:string)=>{if(v.trim()===''||!Number.isFinite(Number(v)))return;set(Math.max(min,Math.min(max,Number(v))));this.changed();};range.oninput=()=>update(range.value);number.onchange=()=>update(number.value);this.bindings.push(()=>{range.value=number.value=String(get());});
 }
 private changed(){try{localStorage.setItem('city-grading-draft-v1',JSON.stringify(this.value));}catch{}this.apply(this.bypass?defaultGrade():this.value);this.sync();}
 private sync(){this.bindings.forEach(f=>f());const points=this.value.curves[this.channel].map((v,i)=>`${8+i*60},${136-v*128}`);this.panel.querySelector('polyline')!.setAttribute('points',points.join(' '));this.panel.querySelectorAll('circle').forEach((c,i)=>{const [x,y]=points[i].split(',');c.setAttribute('cx',x);c.setAttribute('cy',y);});(document.getElementById('grade-json') as HTMLTextAreaElement).value=JSON.stringify(this.value,null,2);const compare=document.getElementById('grade-compare')!;compare.textContent=this.bypass?'正在看原图 · 返回调色':'对比原图';compare.setAttribute('aria-pressed',String(this.bypass));}
}

