import {defaultSky,type SkyPalette} from '../scenes/SkyGradient';
export class SkyPalettePanel{
 constructor(apply:(p:SkyPalette)=>void){
  let value=defaultSky();try{const saved=JSON.parse(localStorage.getItem('city-sky-palette-v1')??'null');if(saved&&/^#[0-9a-f]{6}$/i.test(saved.sky)&&/^#[0-9a-f]{6}$/i.test(saved.background)&&Number.isFinite(saved.transition)&&saved.transition>=.15&&saved.transition<=.85)value=saved;}catch{}
  const open=document.createElement('button');open.textContent='◒ 背景色盘';open.id='sky-settings';document.querySelector('.pause-panel .weather-actions')!.prepend(open);
  const panel=document.createElement('section');panel.id='sky-panel';panel.hidden=true;panel.innerHTML=`<header><b>背景 → 天空渐变</b><button id="sky-close">返回</button></header><label>天空颜色 <input id="sky-top" type="color"></label><label>背景颜色 <input id="sky-bottom" type="color"></label><label>渐变位置 <input id="sky-transition" type="range" min="0.15" max="0.85" step="0.01"></label><div id="sky-swatch"></div><small>实时预览 · 夜晚自动变暗 · 参数保存在本机</small><div><button id="sky-reset">恢复默认</button><button id="sky-copy">复制参数</button></div><textarea id="sky-json" readonly aria-label="背景渐变参数"></textarea><output id="sky-status" role="status"></output>`;document.getElementById('pause-menu')!.append(panel);
  const top=panel.querySelector('#sky-top') as HTMLInputElement,bottom=panel.querySelector('#sky-bottom') as HTMLInputElement,transition=panel.querySelector('#sky-transition') as HTMLInputElement,json=panel.querySelector('textarea')!;
  const sync=()=>{top.value=value.sky;bottom.value=value.background;transition.value=String(value.transition);json.value=JSON.stringify(value,null,2);(panel.querySelector('#sky-swatch') as HTMLElement).style.background=`linear-gradient(to top,${value.background},${value.sky})`;apply(value);try{localStorage.setItem('city-sky-palette-v1',JSON.stringify(value));}catch{}};
  top.oninput=()=>{value.sky=top.value;sync();};bottom.oninput=()=>{value.background=bottom.value;sync();};transition.oninput=()=>{value.transition=Number(transition.value);sync();};
  open.onclick=()=>{panel.hidden=false;document.body.classList.add('sky-editing');document.getElementById('sky-close')!.focus();};document.getElementById('sky-close')!.onclick=()=>{panel.hidden=true;document.body.classList.remove('sky-editing');open.focus();};document.getElementById('sky-reset')!.onclick=()=>{value=defaultSky();sync();};document.getElementById('sky-copy')!.onclick=async()=>{try{await navigator.clipboard.writeText(json.value);document.getElementById('sky-status')!.textContent='已复制，可以粘贴到聊天';}catch{json.focus();json.select();document.getElementById('sky-status')!.textContent='请全选复制参数';}};
  new MutationObserver(()=>{if(document.getElementById('pause-menu')!.hidden){panel.hidden=true;document.body.classList.remove('sky-editing');}}).observe(document.getElementById('pause-menu')!,{attributes:true,attributeFilter:['hidden']});sync();
 }
}
